name: Remove Triage Label

on:
  issues:
    types:
      - 'assigned'

jobs:
  remove_triage:
    name: "Remove triage label if issue is assigned"
    runs-on: ubuntu-latest
    steps:
      - env:
        TRY_GET_LABELS: github.event.issue.labels
      run: |
        echo $TRY_GET_LABELS